# Generated by Django 4.2.5 on 2023-10-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_picture_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='user',
        ),
    ]
